---

- name: Install block.
  when: '"HPE" in ansible_system_vendor and ansible_product_name is regex("ProLiant [a-zA-Z0-9]+ Gen[0-9]+")'
  block:

    - name: Install dependencies.
      become: true
      ansible.builtin.yum:
        name: "{{ item }}"
        state: present
        update_cache: true
        lock_timeout: 300
      loop: "{{ ansible_role_hpe_ams_dependencies }}"

    - name: Install HPE AMS.
      become: true
      ansible.builtin.yum:
        name: amsd
        state: present
        lock_timeout: 300
      notify: Restart_amsd

    - name: Enable and start HPE AMS service.
      become: true
      ansible.builtin.service:
        name: amsd
        state: started
        enabled: true
