---

- name: Include variables specific for the distribution.
  ansible.builtin.include_vars: "{{ item }}"
  with_items:
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"

- name: Import install tasks.
  ansible.builtin.import_tasks:
    file: install.yml
